import React, { createContext, useContext, useState } from "react";

export const translations = {
  en: {
    // Add to EN section:
    happyPatients: "Happy Patients",
    expertDentists: "Expert Dentists",
    modernClinics: "Modern Clinics",
    daysOpen: "Days Open",
    heroTitle1: "Dental Care",
    heroTitle2: "You Can Trust",
    heroDesc:
      "Advanced technology, expert dentists, and compassionate care — all under one roof.",
    isoCertified: "ISO Certified",
    qualityAssured: "Quality assured",
    acrossIndia: "Across India",
    open7Days: "Open 7 Days",
    includingWeekends: "Including weekends",
    trustedByThousands: "Trusted By Thousands",
    trustedDesc: "Patients who chose excellence in dental care",
    ourServices: "Our Services",
    ourServicesDesc:
      "Comprehensive care from routine checkups to advanced procedures",
    whyChooseMediBridge: "Why Choose MediBridge?",
    whyChooseDesc: "Compassionate care combined with cutting-edge technology.",
    quickEasyBooking: "Quick & easy booking. Our team confirms within 2 hours.",
    whyBookWithUs: "Why Book With Us?",
    instantConfirmation: "Instant Confirmation",
    instantConfirmationDesc: "Within 2 hours via call/SMS",
    isoCertifiedDesc: "Highest hygiene standards",
    zeroHiddenCosts: "Zero Hidden Costs",
    zeroHiddenCostsDesc: "Transparent pricing",
    expertDentistsDesc: "15+ years experience",
    needImmediateHelp: "Need Immediate Help?",
    emergencySupport: "24/7 Emergency support available",
    visitOurClinic: "Visit Our Clinic",
    whatPatientsSay: "What Our Patients Say",
    trustedForQuality: "Trusted by thousands for quality care",
    readyToTransform: "Ready to Transform Your Smile?",
    readyToTransformDesc:
      "Join thousands of satisfied patients and experience dental care like never before.",
    whitening: "Teeth Whitening",
    emergencyCare: "Emergency Care",
    scheduling: "Scheduling...",
    contactUs: "Contact Us",
    contactDesc: "Get in touch with our team. We'll respond within 2 hours.",
    sendMessage: "Send a Message",
    yourMessage: "Your Message",
    messageSent: "Message sent!",
    clinicAddress: "Clinic Address",
    workingHours: "Working Hours",
    monSat: "Mon – Sat",
    sunday: "Sunday",
    dentalEmergency: "Dental Emergency?",
    emergencyDesc: "We provide 24/7 emergency dental care.",
    callEmergencyLine: "Call Emergency Line",
    dentalHealthGuide: "Dental Health Guide",
    awarenessTitle: "Dental Awareness Guidelines",
    awarenessDesc: "Simple habits that protect your smile for a lifetime.",
    tip1Title: "Brush Twice Daily",
    tip1Desc:
      "Use fluoride toothpaste and brush for at least 2 minutes, morning and night.",
    tip2Title: "Reduce Sugar Intake",
    tip2Desc: "Cut down on sugary foods and drinks to prevent tooth decay.",
    tip3Title: "Regular Checkups",
    tip3Desc: "Visit your dentist every 6 months for a professional cleaning.",
    tip4Title: "Wear a Mouthguard",
    tip4Desc: "Protect your teeth during contact sports.",
    tip5Title: "Follow Post-Treatment Care",
    tip5Desc: "Always follow your dentist's advice after any dental procedure.",
    tip6Title: "Floss Daily",
    tip6Desc: "Flossing removes plaque from areas your toothbrush can't reach.",
    dataProtected: "Patient Data Protected",
    dataProtectedDesc:
      "All patient records are stored securely with end-to-end encryption.",
    ratingsFeedback: "Ratings & Feedback",
    ratingDesc: "Share your experience to help us improve our services.",
    leaveReview: "Leave a Review",
    yourComment: "Your Comment",
    submitReview: "Submit Review",
    thanksFeedback: "Thanks for your feedback!",
    latestFeedback: "Latest Feedback",
    noReviews: "No reviews yet. Be the first!",
    excellent: "Excellent",
    good: "Good",
    average: "Average",
    belowAverage: "Below Average",
    poor: "Poor",
    serverError: "Server error. Try later.",
    requestHelp: "Request Emergency Help",
    callDirectly: "Or call directly",
    // Navbar
    home: "Home",
    appointment: "Appointment",
    contact: "Contact",
    awareness: "Awareness",
    reviews: "Reviews",
    myAppointments: "My Appointments",
    admin: "Admin",
    login: "Login",
    logout: "Logout",
    bookNow: "Book Now",
    emergency: "Emergency",
    // Booking
    bookYourAppointment: "Book Your Appointment",
    scheduleYourCare: "Schedule your dental care with our professional team",
    appointmentDetails: "Appointment Details",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    preferredDate: "Preferred Date",
    preferredTime: "Preferred Time",
    serviceType: "Service Type",
    selectTime: "Select time",
    selectService: "Select a service",
    bookAppointment: "Book Appointment",
    bookingSuccess: "Appointment booked successfully!",
    // Services
    generalCheckup: "General Checkup",
    cleaning: "Cleaning",
    implant: "Implant",
    braces: "Braces",
    rootCanal: "Root Canal",
    cosmeticDentistry: "Cosmetic Dentistry",
    // My Appointments
    myAppointmentsTitle: "My Appointments",
    manageVisits: "View and manage your dental visits",
    noAppointments: "No appointments yet",
    noAppointmentsDesc: "Book your first appointment and it will show up here.",
    reschedule: "Reschedule",
    status_pending: "Pending",
    status_approved: "Approved",
    status_completed: "Completed",
    status_rejected: "Rejected",
    date: "Date",
    time: "Time",
    service: "Service",
    doctor: "Doctor",
    status: "Status",
    action: "Action",
    // Reschedule modal
    rescheduleAppointment: "Reschedule Appointment",
    currentBooking: "Current Booking",
    newDate: "New Date",
    newTime: "New Time",
    confirmReschedule: "Confirm Reschedule",
    cancel: "Cancel",
    rescheduledSuccess: "Appointment rescheduled successfully!",
    selectTimeSlot: "Select a time slot",
    // Footer
    quickLinks: "Quick Links",
    services: "Services",
    contactInfo: "Contact Info",
    allRightsReserved: "All rights reserved.",
    whatsappUs: "WhatsApp Us",
    // Why choose us
    whyChooseUs: "Why Choose Us?",
    experiencedProfessionals: "Experienced Professionals",
    experiencedDesc: "Our team of certified dentists has years of experience.",
    quickAppointments: "Quick Appointments",
    quickDesc: "Get scheduled within 24 hours of your preferred time.",
    patientCare: "Patient Care",
    patientDesc: "We prioritize your comfort and well-being above all.",
  },

  hi: {
    happyPatients: "खुश मरीज",
    expertDentists: "विशेषज्ञ दंत चिकित्सक",
    modernClinics: "आधुनिक क्लीनिक",
    daysOpen: "खुलने के दिन",
    heroTitle1: "विश्वसनीय",
    heroTitle2: "दंत चिकित्सा",
    heroDesc:
      "उन्नत तकनीक, विशेषज्ञ दंत चिकित्सक, और सहानुभूतिपूर्ण देखभाल — सब कुछ एक छत के नीचे।",
    isoCertified: "आईएसओ प्रमाणित",
    qualityAssured: "गुणवत्ता सुनिश्चित",
    acrossIndia: "पूरे भारत में",
    open7Days: "सप्ताह के 7 दिन खुला",
    includingWeekends: "सप्ताहांत सहित",
    trustedByThousands: "हजारों द्वारा भरोसा किया गया",
    trustedDesc: "गुणवत्ता देखभाल के लिए हजारों मरीजों द्वारा भरोसा किया गया",
    ourServices: "हमारी सेवाएं",
    ourServicesDesc: "रूटीन चेकअप से लेकर उन्नत प्रक्रियाओं तक व्यापक देखभाल",
    whyChooseMediBridge: "मेडीब्रिज क्यों चुनें?",
    whyChooseDesc: "सहानुभूतिपूर्ण देखभाल जो अत्याधुनिक तकनीक के साथ मिलती है।",
    quickEasyBooking:
      "त्वरित और आसान बुकिंग। हमारी टीम 2 घंटे के भीतर पुष्टि करती है।",
    whyBookWithUs: "हमारे साथ बुक क्यों करें?",
    instantConfirmation: "तुरंत पुष्टि",
    instantConfirmationDesc: "2 घंटे के भीतर कॉल/एसएमएस के माध्यम से",
    isoCertifiedDesc: "उच्चतम स्वच्छता मानक",
    zeroHiddenCosts: "कोई छिपे हुए शुल्क नहीं",
    zeroHiddenCostsDesc: "पारदर्शी मूल्य निर्धारण",
    expertDentistsDesc: "15+ वर्षों का अनुभव",
    needImmediateHelp: "तुरंत मदद चाहिए?",
    emergencySupport: "24/7 आपातकालीन सहायता उपलब्ध",
    visitOurClinic: "हमारे क्लिनिक पर आएं",
    whatPatientsSay: "हमारे मरीज क्या कहते हैं",
    trustedForQuality: "गुणवत्ता देखभाल के लिए हजारों द्वारा भरोसा किया गया",
    readyToTransform: "अपनी मुस्कान को बदलने के लिए तैयार?",
    readyToTransformDesc:
      "हजारों संतुष्ट मरीजों में शामिल हों और पहले कभी नहीं जैसी दंत चिकित्सा देखभाल का अनुभव करें।",
    whitening: "दांतों को सफेद करना",
    emergencyCare: "आपातकालीन देखभाल",
    scheduling: "निर्धारण...",
    contactUs: "संपर्क करें",
    contactDesc: "हमारी टीम से संपर्क करें। हम 2 घंटे के भीतर जवाब देंगे।",
    sendMessage: "एक संदेश भेजें",
    yourMessage: "आपका संदेश",
    messageSent: "संदेश भेज दिया!",
    clinicAddress: "क्लिनिक का पता",
    workingHours: "काम करने के घंटे",
    monSat: "सोम – शनि",
    sunday: "रविवार",
    dentalEmergency: "दंत आपातकाल?",
    emergencyDesc: "हम 24/7 आपातकालीन दंत देखभाल प्रदान करते हैं।",
    callEmergencyLine: "आपातकालीन लाइन पर कॉल करें",
    dentalHealthGuide: "दंत जागरूकता गाइड",
    awarenessTitle: "दंत जागरूकता दिशानिर्देश",
    awarenessDesc: "सरल आदतें जो आपके जीवन भर की मुस्कान की रक्षा करती हैं।",
    tip1Title: "दिन में दो बार ब्रश करें",
    tip1Desc:
      "फ्लोराइड टूथपेस्ट का उपयोग करें और सुबह और रात को कम से कम 2 मिनट तक ब्रश करें।",
    tip2Title: "चीनी का सेवन कम करें",
    tip2Desc:
      "दांतों के क्षय को रोकने के लिए मीठे खाद्य पदार्थों और पेय पदार्थों को कम करें।",
    tip3Title: "नियमित जांच",
    tip3Desc:
      "एक पेशेवर सफाई के लिए हर 6 महीने में अपने दंत चिकित्सक से मिलें।",
    tip4Title: "माउथगार्ड पहनें",
    tip4Desc: "संपर्क खेलों के दौरान अपने दांतों की रक्षा करें।",
    tip5Title: "उपचार के बाद की देखभाल का पालन करें",
    tip5Desc:
      "किसी भी दंत प्रक्रिया के बाद अपने दंत चिकित्सक की सलाह का हमेशा पालन करें।",
    tip6Title: "रोजाना फ्लॉस करें",
    tip6Desc:
      "फ्लॉसिंग उन क्षेत्रों से प्लाक को हटाती है जहां आपका टूथब्रश नहीं पहुंच सकता।",
    dataProtected: "रोगी डेटा सुरक्षित",
    dataProtectedDesc:
      "सभी रोगी रिकॉर्ड सुरक्षित रूप से एंड-टू-एंड एन्क्रिप्शन के साथ संग्रहीत किए जाते हैं।",
    ratingsFeedback: "रेटिंग और प्रतिक्रिया",
    ratingDesc: "हमारी सेवाओं में सुधार के लिए अपना अनुभव साझा करें।",
    leaveReview: "एक समीक्षा छोड़ें",
    yourComment: "आपकी टिप्पणी",
    submitReview: "समीक्षा सबमिट करें",
    thanksFeedback: "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    latestFeedback: "ताज़ा प्रतिक्रिया",
    noReviews: "अभी तक कोई समीक्षा नहीं। पहला बनें!",
    excellent: "उत्कृष्ट",
    good: "अच्छा",
    average: "औसत",
    belowAverage: "औसत से नीचे",
    poor: "खराब",
    serverError: "सर्वर त्रुटि। बाद में प्रयास करें।",
    requestHelp: "आपातकालीन सहायता का अनुरोध करें",
    callDirectly: "या सीधे कॉल करें",
    // Navbar
    home: "होम",
    appointment: "अपॉइंटमेंट",
    contact: "संपर्क",
    awareness: "जागरूकता",
    reviews: "समीक्षाएं",
    myAppointments: "मेरी अपॉइंटमेंट",
    admin: "एडमिन",
    login: "लॉगिन",
    logout: "लॉगआउट",
    bookNow: "अभी बुक करें",
    emergency: "आपातकाल",
    bookYourAppointment: "अपनी अपॉइंटमेंट बुक करें",
    scheduleYourCare:
      "हमारी पेशेवर टीम के साथ अपनी दंत चिकित्सा निर्धारित करें",
    appointmentDetails: "अपॉइंटमेंट विवरण",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    phoneNumber: "फ़ोन नंबर",
    preferredDate: "पसंदीदा तारीख",
    preferredTime: "पसंदीदा समय",
    serviceType: "सेवा प्रकार",
    selectTime: "समय चुनें",
    selectService: "सेवा चुनें",
    bookAppointment: "अपॉइंटमेंट बुक करें",
    bookingSuccess: "अपॉइंटमेंट सफलतापूर्वक बुक हो गई!",
    generalCheckup: "सामान्य जांच",
    cleaning: "सफाई",
    implant: "इम्प्लांट",
    braces: "ब्रेसेस",
    rootCanal: "रूट कैनाल",
    cosmeticDentistry: "कॉस्मेटिक दंत चिकित्सा",
    myAppointmentsTitle: "मेरी अपॉइंटमेंट",
    manageVisits: "अपनी डेंटल विज़िट देखें और प्रबंधित करें",
    noAppointments: "अभी तक कोई अपॉइंटमेंट नहीं",
    noAppointmentsDesc: "अपनी पहली अपॉइंटमेंट बुक करें और यह यहाँ दिखाई देगी।",
    reschedule: "पुनर्निर्धारित करें",
    status_pending: "लंबित",
    status_approved: "स्वीकृत",
    status_completed: "पूर्ण",
    status_rejected: "अस्वीकृत",
    date: "तारीख",
    time: "समय",
    service: "सेवा",
    doctor: "डॉक्टर",
    status: "स्थिति",
    action: "कार्रवाई",
    rescheduleAppointment: "अपॉइंटमेंट पुनर्निर्धारित करें",
    currentBooking: "वर्तमान बुकिंग",
    newDate: "नई तारीख",
    newTime: "नया समय",
    confirmReschedule: "पुष्टि करें",
    cancel: "रद्द करें",
    rescheduledSuccess: "अपॉइंटमेंट सफलतापूर्वक पुनर्निर्धारित हो गई!",
    selectTimeSlot: "समय स्लॉट चुनें",
    quickLinks: "त्वरित लिंक",
    services: "सेवाएं",
    contactInfo: "संपर्क जानकारी",
    allRightsReserved: "सर्वाधिकार सुरक्षित।",
    whatsappUs: "व्हाट्सएप करें",
    whyChooseUs: "हमें क्यों चुनें?",
    experiencedProfessionals: "अनुभवी पेशेवर",
    experiencedDesc:
      "हमारी प्रमाणित दंत चिकित्सकों की टीम के पास वर्षों का अनुभव है।",
    quickAppointments: "त्वरित अपॉइंटमेंट",
    quickDesc: "आपके पसंदीदा समय के 24 घंटे के भीतर निर्धारित हों।",
    patientCare: "रोगी देखभाल",
    patientDesc: "हम आपके आराम और कल्याण को सर्वोपरि रखते हैं।",
  },

  mr: {
    happyPatients: "आनंदी रुग्ण",
    expertDentists: "तज्ञ दंतचिकित्सक",
    modernClinics: "आधुनिक क्लिनिक",
    daysOpen: "खुल्या दिवस",
    heroTitle1: "विश्वसनीय",
    heroTitle2: "दंत चिकित्सा",
    heroDesc:
      "उन्नत तंत्रज्ञान, तज्ञ दंतचिकित्सक, आणि सहानुभूतिपूर्ण देखभाल — सर्व एकाच छताखाली.",
    isoCertified: "आयएसओ प्रमाणित",
    qualityAssured: "गुणवत्ता सुनिश्चित",
    acrossIndia: "संपूर्ण भारतात",
    open7Days: "सप्ताहात 7 दिवस खुले",
    includingWeekends: "सप्ताहांत सहित",
    trustedByThousands: "हजारों द्वारा भरोसा किया गया",
    trustedDesc: "गुणवत्ता देखभाल के लिए हजारों मरीजों द्वारा भरोसा किया गया",
    ourServices: "आमच्या सेवा",
    ourServicesDesc: "रूटीन चेकअप से लेकर उन्नत प्रक्रियाओं तक व्यापक देखभाल",
    whyChooseMediBridge: "मेडीब्रिज क्यों चुनें?",
    whyChooseDesc: "सहानुभूतिपूर्ण देखभाल जो अत्याधुनिक तकनीक के साथ मिलती है।",
    quickEasyBooking:
      "त्वरित और आसान बुकिंग। हमारी टीम 2 घंटे के भीतर पुष्टि करती है।",
    whyBookWithUs: "हमारे साथ बुक क्यों करें?",
    instantConfirmation: "तुरंत पुष्टि",
    instantConfirmationDesc: "2 घंटे के भीतर कॉल/एसएमएस के माध्यम से",
    isoCertifiedDesc: "उच्चतम स्वच्छता मानक",
    zeroHiddenCosts: "कोई छिपे हुए शुल्क नहीं",
    zeroHiddenCostsDesc: "पारदर्शी मूल्य निर्धारण",
    expertDentistsDesc: "15+ वर्षों का अनुभव",
    needImmediateHelp: "तुरंत मदद चाहिए?",
    emergencySupport: "24/7 आपातकालीन सहायता उपलब्ध",
    visitOurClinic: "हमारे क्लिनिक पर आएं",
    whatPatientsSay: "हमारे मरीज क्या कहते हैं",
    trustedForQuality: "गुणवत्ता देखभाल के लिए हजारों द्वारा भरोसा किया गया",
    readyToTransform: "अपनी मुस्कान को बदलने के लिए तैयार?",
    readyToTransformDesc:
      "हजारों संतुष्ट मरीजों में शामिल हों और पहले कभी नहीं जैसी दंत चिकित्सा देखभाल का अनुभव करें।",
    whitening: "दांतों को सफेद करना",
    emergencyCare: "आपातकालीन देखभाल",
    scheduling: "निर्धारण...",
    contactUs: "संपर्क करें",
    contactDesc: "हमारी टीम से संपर्क करें। हम 2 घंटे के भीतर जवाब देंगे।",
    sendMessage: "एक संदेश भेजें",
    yourMessage: "आपका संदेश",
    messageSent: "संदेश भेज दिया!",
    clinicAddress: "क्लिनिक का पता",
    workingHours: "काम करने के घंटे",
    monSat: "सोम – शनि",
    sunday: "रविवार",
    dentalEmergency: "दंत आपातकाल?",
    emergencyDesc: "हम 24/7 आपातकालीन दंत देखभाल प्रदान करते हैं।",
    callEmergencyLine: "आपातकालीन लाइन पर कॉल करें",
    dentalHealthGuide: "दंत जागरूकता गाइड",
    awarenessTitle: "दंत जागरूकता दिशानिर्देश",
    awarenessDesc: "सरल आदतें जो आपके जीवन भर की मुस्कान की रक्षा करती हैं।",
    tip1Title: "दिन में दो बार ब्रश करें",
    tip1Desc:
      "फ्लोराइड टूथपेस्ट का उपयोग करें और सुबह और रात को कम से कम 2 मिनट तक ब्रश करें।",
    tip2Title: "चीनी का सेवन कम करें",
    tip2Desc:
      "दांतों के क्षय को रोकने के लिए मीठे खाद्य पदार्थों और पेय पदार्थों को कम करें।",
    tip3Title: "नियमित जांच",
    tip3Desc:
      "एक पेशेवर सफाई के लिए हर 6 महीने में अपने दंत चिकित्सक से मिलें।",
    tip4Title: "माउथगार्ड पहनें",
    tip4Desc: "संपर्क खेलों के दौरान अपने दांतों की रक्षा करें।",
    tip5Title: "उपचार के बाद की देखभाल का पालन करें",
    tip5Desc:
      "किसी भी दंत प्रक्रिया के बाद अपने दंत चिकित्सक की सलाह का हमेशा पालन करें।",
    tip6Title: "रोजाना फ्लॉस करें",
    tip6Desc:
      "फ्लॉसिंग उन क्षेत्रों से प्लाक को हटाती है जहां आपका टूथब्रश नहीं पहुंच सकता।",
    dataProtected: "रोगी डेटा सुरक्षित",
    dataProtectedDesc:
      "सभी रोगी रिकॉर्ड सुरक्षित रूप से एंड-टू-एंड एन्क्रिप्शन के साथ संग्रहीत किए जाते हैं।",
    ratingsFeedback: "रेटिंग और प्रतिक्रिया",
    ratingDesc: "हमारी सेवाओं में सुधार के लिए अपना अनुभव साझा करें।",
    leaveReview: "एक समीक्षा छोड़ें",
    yourComment: "आपकी टिप्पणी",
    submitReview: "समीक्षा सबमिट करें",
    thanksFeedback: "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    latestFeedback: "ताज़ा प्रतिक्रिया",
    noReviews: "अभी तक कोई समीक्षा नहीं। पहला बनें!",
    excellent: "उत्कृष्ट",
    home: "मुखपृष्ठ",
    appointment: "भेट",
    contact: "संपर्क",
    awareness: "जागरूकता",
    reviews: "पुनरावलोकने",
    myAppointments: "माझ्या भेटी",
    admin: "प्रशासक",
    login: "लॉगिन",
    logout: "लॉगआउट",
    bookNow: "आत्ता बुक करा",
    emergency: "आणीबाणी",
    bookYourAppointment: "आपली भेट बुक करा",
    scheduleYourCare: "आमच्या व्यावसायिक टीमसह आपली दंत काळजी निश्चित करा",
    appointmentDetails: "भेटीचा तपशील",
    fullName: "पूर्ण नाव",
    emailAddress: "ईमेल पत्ता",
    phoneNumber: "फोन नंबर",
    preferredDate: "पसंतीची तारीख",
    preferredTime: "पसंतीची वेळ",
    serviceType: "सेवा प्रकार",
    selectTime: "वेळ निवडा",
    selectService: "सेवा निवडा",
    bookAppointment: "भेट बुक करा",
    bookingSuccess: "भेट यशस्वीरित्या बुक झाली!",
    generalCheckup: "सामान्य तपासणी",
    cleaning: "सफाई",
    implant: "इम्प्लांट",
    braces: "ब्रेसेस",
    rootCanal: "रूट कॅनाल",
    cosmeticDentistry: "सौंदर्यात्मक दंतचिकित्सा",
    myAppointmentsTitle: "माझ्या भेटी",
    manageVisits: "आपल्या दंत भेटी पहा आणि व्यवस्थापित करा",
    noAppointments: "अद्याप कोणतीही भेट नाही",
    noAppointmentsDesc: "आपली पहिली भेट बुक करा आणि ती येथे दिसेल.",
    reschedule: "पुनर्निर्धारित करा",
    status_pending: "प्रलंबित",
    status_approved: "मंजूर",
    status_completed: "पूर्ण",
    status_rejected: "नाकारले",
    date: "तारीख",
    time: "वेळ",
    service: "सेवा",
    doctor: "डॉक्टर",
    status: "स्थिती",
    action: "कृती",
    rescheduleAppointment: "भेट पुनर्निर्धारित करा",
    currentBooking: "सध्याची बुकिंग",
    newDate: "नवीन तारीख",
    newTime: "नवीन वेळ",
    confirmReschedule: "पुष्टी करा",
    cancel: "रद्द करा",
    rescheduledSuccess: "भेट यशस्वीरित्या पुनर्निर्धारित झाली!",
    selectTimeSlot: "वेळ स्लॉट निवडा",
    quickLinks: "द्रुत दुवे",
    services: "सेवा",
    contactInfo: "संपर्क माहिती",
    allRightsReserved: "सर्व हक्क राखीव.",
    whatsappUs: "व्हाट्सअ‍ॅप करा",
    whyChooseUs: "आम्हाला का निवडा?",
    experiencedProfessionals: "अनुभवी व्यावसायिक",
    experiencedDesc:
      "आमच्या प्रमाणित दंतचिकित्सकांच्या टीमला वर्षांचा अनुभव आहे.",
    quickAppointments: "जलद भेटी",
    quickDesc: "आपल्या पसंतीच्या वेळेच्या २४ तासांत निर्धारित व्हा.",
    patientCare: "रुग्ण सेवा",
    patientDesc: "आम्ही आपला आराम आणि कल्याण सर्वोपरि ठेवतो.",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("language") || "en",
  );

  const t = (key) =>
    translations[language]?.[key] ?? translations["en"]?.[key] ?? key;

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
